### ISSUE TITLE
Реализовать настоящую асинхронную обработку изображений.

### ISSUE THREAD

**Issue by egortech** [koveev/Mallenom.ImageProcessing#1]
Необходимо реализовать "правильную" асинхронную обработку изображений, так чтобы код контрастирования и наложения градиента выполнялся в отдельном потоке.

Эти функции должны возвращать Task<Bitmap>, принимать параметры обработки и исходный Bitmap.

Запрос на обработку должен выполнять одновременно один, при этом самых последний должен гарантированно выполниться (когда пользователь пересталь менять положение ползунка.)

**Comment by egortech** [comment]
+ Убедиться, что для всех обработанных изображений вызывается ``Dispose``, когда они становятся не нужны.

**Comment by koveev** [comment]
Да, уже сделал, спасибо.
Скоро залью

Ср, 18 авг. 2021 г. в 16:18, Volkov Egor ***@***.***>:

**Comment by koveev** [comment]
Единственное, bitmap внутри Таска диспоузить не даёт, так как он ещё
используется.
Поэтому и чищу глобальный bitmap.
Это нормально, или ещё подумать?

Ср, 18 авг. 2021 г. в 16:23, Volkov Egor ***@***.***>:

**Comment by egortech** [comment]
Как я говорил тут много где можно выстрелить в ногу. Твой вариант с lock к сожалению тут не поможет так, как он по сути гарантирует лишь то, что одновременно не будет применяться обработка, но приводит к тому, что всё равно будет выполнена обработка каждого движения ползунка. Что приведёт потенциально очень большой нагрузки на CPU и OutOfMemory. Ползунок может спокойно одним движением генерировать 50-100 событий и тебя будет последовательно эти запосы обрабатываться.

![image](https://user-images.githubusercontent.com/13813684/129944795-c211f4b6-4841-4dc4-9177-3d097ad6b320.png)

![image](https://user-images.githubusercontent.com/13813684/129944838-d27aeecc-ba69-4d1e-8ec8-ed5caa18a5dc.png)

Надо подумать ещё

**Comment by egortech** [comment]
Ещё увидел очень опасный антипаттерн, что ты не делаешь await у Task. По итогу ты в 52 строчке вообще не будешь ждать, так как ты возвращашь Task в методе ``GradientProccessing``, которых просто выкидываешь и дожидаешься его выполнения.

**Comment by egortech** [comment]
https://markheath.net/post/async-antipatterns

**Comment by koveev** [comment]
Уточняющий вопрос, с этим кодом это возможно?Или проще переписать?

**Comment by egortech** [comment]
Возможно. Остаётся написать лишь условие запуска асинхронной задачи.

**Comment by koveev** [comment]
Получилось в несколько раз уменьшить потребление памяти, ограничить ее потребление, как в случае с GradientProccessing  пока не получается.

**Comment by koveev** [comment]
Обновил.
